---
apt_packages:
  - alacritty
  - i3-wm
  - libreoffice
  - nitrogen
  - tmux
  - vim
  - gnupg # for terraform
  - software-properties-common # for terraform
  - awscli
    # - terraform
    # - kubectl

apt_repositories:
  - ppa:aslatter/ppa # for alacritty

uninstall_packages:
  - firefox
