---
- name: Check if cargo is installed
  shell: cargo --version
  register: cargo_version
  ignore_errors: true

- name: Download the rustup installer
  get_url:
    url: https://sh.rustup.rs
    dest: ~/Downloads/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  when: cargo_version.failed 

- name: Run the rustup installer
  shell: ~/Downloads/sh.rustup.rs -y
  when: cargo_version.failed

- name: Add the standard library sources (required for rust-analyzer)
  shell: rustup component add rust-src

- name: Install rust-analyzer
  shell: rustup component add rust-analyzer
...
