---
- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ create_directories }}"
     
    # - name: Clone personal public repositories
    #   git:
    #     repo: "{{ item.repo }}"
    #     dest: "{{ item.dest }}"
    #     version: "{{ item.version }}"
    #   loop: "{{ personal_repositories_public }}"

- name: Create OS specific branch to be used by the OS
  shell:
    cmd: echo "TODO"

- name: Create dotfile links
  shell:
    cmd: echo "TODO"

- name: Setup change detection job
  shell:
    cmd: echo "TODO"

- name: Setup auto pull on boot job
  shell:
    cmd: echo "TODO"
...
