---
- name: Set up directories
  ansible.builtin.shell:
    cmd: mkdir -p {{ item }}
  loop: "{{ create_directories }}"
     
- name: Clone .dotfiles repository
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
  loop: "{{ personal_repositories_public }}"

- name: Install other package requirements 
  ansible.builtin.shell:
    cmd: echo "TODO"

- name: Create OS specific branch to be used by the OS
  ansible.builtin.shell:
    cmd: echo "TODO"

- name: Create dotfile links
  ansible.builtin.shell:
    cmd: echo "TODO"

- name: Setup change detection job
  ansible.builtin.shell:
    cmd: echo "TODO"

- name: Setup auto pull on boot job
  ansible.builtin.shell:
    cmd: echo "TODO"
