---
pacman_packages:
  - alacritty
  - archlinux-wallpaper
  - arandr
  - arc-gtk-theme
  - base-devel
  - cheese
  - conky
  - cups
  - discord
  - docker
  - docker-buildx
  - docker-compose
  - dmenu
  - gedit
  - gimp
  - gnome-system-monitor
  - i3-gaps
  - i3-wm
  - i3blocks
  - i3lock
  - i3status
  - jq
  - libreoffice
  - lightdm
  - lightdm-gtk-greeter
  - lxappearance
  - minikube
  - neovim
  - nitrogen
  - noto-fonts
  - numlockx
  - nvidia
  - nvidia-utils
  - obs-studio
  - obsidian
  - papirus-icon-theme
  - ranger
  - rofi
  - steam
  - sqlite
  - sxiv
  - terminator
  - tmux
  - ttf-dejavu
  - ttf-freefont
  - ttf-ubuntu-font-family
  - wget
  - xorg-apps
  - xorg-server
  - xorg-xinit
  - zsh
...
