---
pacman_packages:
  - alacritty
  - arandr
  - base-devel
  - conky
  - cups
  - discord
  - docker
  - docker-buildx
  - docker-compose
  - gnome
  - gnome-tweaks
  - i3-wm
  - i3status
  - jq
  - nitrogen
  - libreoffice
  - neovim
  - nvidia
  - nvidia-utils
  - obs-studio
  - obsidian
  - steam
  - tmux
  - xorg-server
  - xorg-xinit
...
