---
- name: Clone yay repository
  git:
    repo: "{{ source.url }}"
    dest: "{{ source.dest }}"

- name: Make the yay package
  command:
    chdir: "{{ source.dest }}"
    cmd: "makepkg -sfi --noconfirm"

- name: Remove the yay directory
  file:
    path: "{{ source.dest }}"
    state: absent

- name: Install yay packages
  yay:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ packages }}"
  become: true
  become_method: sudo

- name: Enable xboxdrv
  service:
    name: xboxdrv
    enabled: true

...
