---
- name: Start docker service (effective on reboot)
  service:
    name: docker
    enabled: yes
  become: true
  become_method: sudo

- name: Get current user
  shell: whoami
  register: current_user

- name: Add current user to docker group
  user:
    name: current_user.stdout
    groups: docker
    append: yes
  become: true
  become_method: sudo
...
