---
- name: Update and upgrade apt
  apt:
    update_cache: yes
    upgrade: "yes"
  become: true
  become_method: sudo

- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ apt_repositories }}"
  become: true
  become_method: sudo

- name: Install apt package requirements
  apt:
    pkg:
      - "{{ item }}"
  loop: "{{ apt_packages }}"
  become: true
  become_method: sudo
