---
- name: Enable lightdm display manager service
  service:
    name: lightdm
    enabled: yes
  become: true
  become_method: sudo

- name: Create lightdm config directory
  file:
    path: "/etc/lightdm"
    state: directory
  become: true
  become_method: sudo

- name: Symlink lightdm configuration
  file:
    src: "{{ config_location }}"
    dest: "{{ symlink_dest }}"
    state: link
    force: true
  become: true
  become_method: sudo
...
