---
- name: Enable multilib repositories
  lineinfile:
    path: /etc/pacman.conf
    insertafter: "EOF"
    replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
  become: true
  become_method: sudo

- name: Update all base pacman packages
  pacman:
    update_cache: yes
    upgrade: yes
  become: true
  become_method: sudo

- name: Install pacman packages
  pacman:
    name: "{{ item }}"
    state: latest
  loop: "{{ pacman_packages }}"
  become: true
  become_method: sudo

    # - name: Start GNOME service (effective on reboot)
    #   service:
    #     name: gdm
    #     enabled: yes

- name: Start lightdm display manager service (effective on reboot)
  service:
    name: lightdm
    enabled: yes
...
