---
- name: Enable multilib repositories
  blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE ENABLED MULTILIB BLOCK"
    marker_begin: "START"
    marker_end: "END"
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  become: true
  become_method: sudo

- name: Update all base pacman packages
  pacman:
    update_cache: yes
    upgrade: yes
  become: true
  become_method: sudo

- name: Install pacman packages
  pacman:
    name: "{{ item }}"
    state: latest
    extra_args: --overwrite "*"
  loop: "{{ pacman_packages }}"
  become: true
  become_method: sudo
...
